#!/bin/bash
source ~/dl_binder_design/mpnn_fastrelax_env/bin/activate
# Check if $1 exists in the current directory
if [[ ! -e $1 ]]; then
    echo "$1 not found in the current directory"
    exit 1
fi

# Check if $1, $2, and $3 are specified
if [[ -z $1 || -z $2 || -z $3 ]]; then
    echo "Usage: $0 <input_file> <relax_cycles> <seqs_per_struct>"
    exit 1
fi

# Set a default value for number of cpus if not specified
if [[ -z $4 ]]; then
    cpus=14
else
    cpus=$4
fi

# Start the timer
start_time=$(date +%s)

#Count the number of PDB files in the silent file
count=$(silentls "$1" | wc -l)
echo $count " PDB files"
mkdir .tmp
cd .tmp
echo "Using $cpus CPUs"

#Calculate the number of splits by dividing the number of PDB files by the number of CPUs
split=$(echo "scale=0; $count / $cpus" | bc)

# Split the file into smaller files
silentsplit $1 $split

# Run proteinmpnn in parallel
find . -name "x*" | parallel -j $cpus dl_interface_design.py -silent {} -relax_cycle $2 -seqs_per_struct $3 -outsilent {}_out.silent -checkpoint_name {}_check.point -temp_name {}_temp.pdb

# Create the new filenames
filename=$1
temp_name=${filename%_designs*.silent}
date=${temp_name%_*}
job_id=${temp_name##*_}
new_filename="${date}_${job_id}_relax_cycles_${2}_seqs_per_struct_${3}"

# Merge the output files
cat *out.silent > ${new_filename}.silent
cat *check.point > ${new_filename}_check.point

# Clean up
cd ..
rm -rf .tmp

# Calculate the elapsed time
end_time=$(date +%s)
elapsed_time=$((end_time - start_time))

minutes=$((elapsed_time / 60))
seconds=$((elapsed_time % 60))

echo "It took $minutes minutes and $seconds seconds to run the script."
# End of script